### ISSUE TITLE
End to end example using ddp (Distributed Data Parallel) strategy.

### ISSUE THREAD

**Issue by mosheraboh** [BiomedSciAI/fuse-med-ml#117]

**Comment by mosheraboh** [comment]
It will require to resolve an issue in pytorch lightning:
https://github.com/Lightning-AI/lightning/issues/11807

**Comment by SagiPolaczek** [comment]
Currently paused the PR due internal [PyTorch-Lightning issue](https://github.com/Lightning-AI/lightning/issues/4450).

Note that the MNIST DDP runner runs OK without our custom sampler.
