### ISSUE TITLE
Test and declare support in python 3.8 and 3.9

### ISSUE THREAD

**Issue by mosheraboh** [BiomedSciAI/fuse-med-ml#144]
**Is your feature request related to a problem? Please describe.**
Using FuseMedML with python 3.8 and 3.9
 
**Describe the solution you'd like**
run all the tests (run_all_unit_tests.sh) with python 3.8 and 3.9. Fix tests that fail if those exist.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by SagiPolaczek** [comment]
@mosheraboh 
We did test the last PRs with 3.7-3.10. Is that enough?

**Comment by SagiPolaczek** [comment]
Close for now.
