### ISSUE TITLE
Start training on CPU if couldnt auto detect GPU/s

### ISSUE THREAD

**Issue by smartdanny** [BiomedSciAI/fuse-med-ml#190]
**Describe the bug**\
If fuse does not auto-detect any GPU, it will just stop raise Exception. Instead I think we should continue with cpu (and leaving a warning saying so)

**FuseMedML version**: 0.2.4

**Python version**: Python 3.10.4

**To reproduce**\
Run MNIST example without gpu (m1 mac)

**Expected behavior**\
Start Running on CPU.

**Additional context**\
Solvable in `utils/gpu.py`:
```
if available_gpu_ids is None:
    raise Exception("could not auto-detect available GPUs")
```

**Comment by mosheraboh** [comment]
Thanks @smartdanny !
You can modify the code to something like:
num_allocated = choose_and_enable_multiple_gpus(UM_GPUS, force_gpus=force_gpus, use_cpu_if_fail=True)
if num_allocated == 0:
    TRAIN_COMMON_PARAMS["trainer.accelerator"] = "cpu"

BTW, we test fusemedml only on linux servers. Let me know if you have any IOS-related issues.

**Comment by smartdanny** [comment]
right, using use_cpu_if_fail fixed :) thanks
