### ISSUE TITLE
Can't install both fuse and tensorflow

### ISSUE THREAD

**Issue by alex-golts** [BiomedSciAI/fuse-med-ml#223]
Currently FuseMedML (v0.2.9) requires protobuf version 3.20 but (pip installable) tensorflow (v2.11.0) requires <3.20.
Can we resolve this somehow? Thanks!

**Comment by mosheraboh** [comment]
Hi!
3.20 caused some dependency issues to 3rd party libraries.
It was probably fixed already.
Please remove the line from fuse/requirements.txt (we don't use protobuf directly). If it will work we can push it to master.
CC @SagiPolaczek who once checked it.

**Comment by alex-golts** [comment]
thanks! done this here:
https://github.com/BiomedSciAI/fuse-med-ml/pull/225
