### ISSUE TITLE
State of the field section missing from the fuse-med-ML paper

### ISSUE THREAD

**Issue by anupamajha1** [BiomedSciAI/fuse-med-ml#229]
According to the JOSS review guidelines, the authors should provide a section titled 'State of the field' which describes how this software compares to other commonly-used packages. This section is currently missing from the [Fuse-Med-ML paper](https://github.com/BiomedSciAI/fuse-med-ml/blob/joss_paper/paper/paper.md).

**Comment by alex-golts** [comment]
Added a "state of the field" section. [see here](https://github.com/BiomedSciAI/fuse-med-ml/blob/joss_paper/paper/paper.md)

**Comment by anupamajha1** [comment]
The state of the field section compares with existing tools.
