### ISSUE TITLE
Add example to Fuse.dl section in the Fuse-med ML paper

### ISSUE THREAD

**Issue by anupamajha1** [BiomedSciAI/fuse-med-ml#230]
Examples in fuse.data and fuse.ml sections are extremely useful. Please expand fuse.dl section to include a similar example to explain its functionality.

**Comment by alex-golts** [comment]
@anupamajha1 did you mean the examples in the readme? the fuse.dl readme pointed to some end to end examples, but I now added explicit code blocks to the readme to make it more clear. you can see it in [this PR](https://github.com/BiomedSciAI/fuse-med-ml/pull/232) which is now merged to master. 
Please let me know if you were thinking of something different.

**Comment by alex-golts** [comment]
It later occurred to me that you most likely meant adding an example to the `fuse.dl` section in the paper itself and not in the code readme. So I also added one. please see [updated file here](https://github.com/BiomedSciAI/fuse-med-ml/blob/joss_paper/paper/paper.md).

**Comment by anupamajha1** [comment]
Thanks for adding the figure.
