### ISSUE TITLE
Uncollate is not needed and slows down training

### ISSUE THREAD

**Issue by avihu111** [BiomedSciAI/fuse-med-ml#267]
During training, every batch goes through uncollate (from dict of batches to list of sample dicts)
This loops over: |dataset| * |keys| 
and is not done with multiprocessing, so it is a major bottleneck. 

This is actually not needed, because we can easily gather batches without looping over the dataset samples.
```
for k in keys:
   torch.cat(batch[k], for batch in batches], dim=0)
```

Attaching the profiler output on my code (50K samples, each sample is a dictionary of ~10 vectors):
![image](https://user-images.githubusercontent.com/39214195/215526602-06c5f820-f2e8-4850-a639-3567d937c808.png)

**Comment by mosheraboh** [comment]
Fixed
