### ISSUE TITLE
I got “NameError: name 'NDict' is not defined”  from ndict.py, how can I fix it

### ISSUE THREAD

**Issue by PIPIWTUES** [BiomedSciAI/fuse-med-ml#322]
<img width="981" alt="截屏2023-06-16 下午3 52 08" src="https://github.com/BiomedSciAI/fuse-med-ml/assets/23076443/581d68ad-793f-4746-9661-c23cf8dc37da">

**Comment by SagiPolaczek** [comment]
Hey 👋 
Thanks for reaching out!

Did you install the package in editable mode? (`pip install -e .`)?
I wasn't able to reproduce it locally using VSCode, even with a blank conda env & uninstalled package.. 

Generally speaking, it can be solved using [forward passing](https://peps.python.org/pep-0484/#forward-references).
For this example the following should work:
```python
class NDict(dict):
    """
    (Lazy) N(ested)Dict - wraps a python dict, and allows to access "nested" elements via '.' separated key desc ...
    """

    def __init__(
        self, dict_like: Union[dict, tuple, types.GeneratorType, 'NDict', None] = None, already_flat: bool = False
    ):
```

**Comment by mosheraboh** [comment]
@weiddyaqhhya , any chance you are using python version < 3.7?

**Comment by weiddyaqhhya** [comment]
> @weiddyaqhhya , any chance you are using python version < 3.7?

Hi，you are right, the python version I am using is 3.6.13

> Hey 👋 Thanks for reaching out!
> 
> Did you install the package in editable mode (`pip install -e .`)? You can view the installation section [here](https://github.com/BiomedSciAI/fuse-med-ml#installation) I wasn't able to reproduce it locally using VSCode, even with a blank conda env & uninstalled package..
> 
> Generally speaking, it can be solved using [forward passing](https://peps.python.org/pep-0484/#forward-references). For this example the following should work:
> 
> ```python
> class NDict(dict):
>     """
>     (Lazy) N(ested)Dict - wraps a python dict, and allows to access "nested" elements via '.' separated key desc ...
>     """
> 
>     def __init__(
>         self, dict_like: Union[dict, tuple, types.GeneratorType, 'NDict', None] = None, already_flat: bool = False
>     ):
> ```

hi, I installed using pypi pip install fuse-med-ml[all], I will try your solution, thanks

**Comment by SagiPolaczek** [comment]
@weiddyaqhhya 
There's no need for the fix I've mentioned. Update your python version to 3.9 (we don't support <3.7) and try again.
See [here](https://docs.python.org/3/whatsnew/3.7.html#:~:text=Usability%2Dwise%2C%20annotations%20now%20support%20forward%20references%2C%20making%20the%20following%20syntax%20valid%3A)

@mosheraboh  nice catch!! :)
