### ISSUE TITLE
Python 3.10 incompatibility

### ISSUE THREAD

**Issue by alex-golts** [BiomedSciAI/fuse-med-ml#58]
Currently fuse is incompatible with Python 3.10.x

for example, I encountered an `ImportError: cannot import name 'Iterable' from 'collections'` 
because they changed the structure of the collections module and it needs to be imported as:
`from collections.abc import Iterable` rather than `from collections import Iterable`

Maybe there are other compatibility issues as well, for now I just reverted back to Python 3.7, but we should solve it sometime...

**Comment by SagiPolaczek** [comment]
I'm attaching the relevant source in the documentation [here](https://docs.python.org/3/whatsnew/3.10.html#removed) for further use.
Also I think we won't be able to support python 3.10 until all of our dependencies will..

**Comment by SagiPolaczek** [comment]
@mosheraboh 

I think I'll add this issue to the stack of my tasks. (ISIC is last runs + now finishing DDP). What is your opinion?

btw:
Just changed two lines in the code and the mnist example is running OK with python 3.10.
Also encountered [this](https://github.com/Lightning-AI/lightning/issues/9980) PL's issue as a reference.
